### ISSUE TITLE
Issue with the latest version of SoraVoice.

### ISSUE THREAD

**Issue by Shadowkillerdragon** [ZhenjianYang/SoraVoice#12]
I tried using the current version of SoraVoice that didn't use the SoraDataEx.ini
While it loads at the start of the game. I get the prompt that say a Voice patch was loaded and I start a new game to check the voices, but no voice from Estelle for FC and SC. 

I rolled back to a older one I had with the SoraDataEx.ini files and it was able to get the voices. Am I just doing something wrong with the files?

**Comment by vparitskiy** [comment]
Can confirm having the same issue.

Ruining in debug mode produces following log.

>! [2018-01-08 21:26:00.168]Starting SoraVoice...
[2018-01-08 21:26:00.172]module info: base = 0x00400000, size = 0x02C22000
[2018-01-08 21:26:00.176]Loading Config...
[2018-01-08 21:26:00.183]Config loaded
[2018-01-08 21:26:00.187]config.Volume = 100
[2018-01-08 21:26:00.191]config.OriginalVoice = 1
[2018-01-08 21:26:00.195]config.AutoPlay = 2
[2018-01-08 21:26:00.198]config.WaitTimePerChar = 60
[2018-01-08 21:26:00.203]config.WaitTimeDialog = 800
[2018-01-08 21:26:00.208]config.WaitTimeDialogVoice = 500
[2018-01-08 21:26:00.211]config.SkipVoice = 1
[2018-01-08 21:26:00.215]config.DisableDududu = 1
[2018-01-08 21:26:00.219]config.DisableDialogSE = 1
[2018-01-08 21:26:00.223]config.ShowInfo = 1
[2018-01-08 21:26:00.227]config.FontName = Microsoft Yahei
[2018-01-08 21:26:00.235]config.FontColor = 0xFFFFFFFF
[2018-01-08 21:26:00.239]config.EnableKeys = 1
[2018-01-08 21:26:00.242]config.SaveChange = 1
[2018-01-08 21:26:00.248]Open resource: voice/SoraData.ini
[2018-01-08 21:26:00.252]Resource openned, first = 0x23B550F8, size = 0x37D6
[2018-01-08 21:26:00.284]ini file opened. 17
[2018-01-08 21:26:00.290]Check data: Sora FC
[2018-01-08 21:26:00.294]game = 1
[2018-01-08 21:26:00.298]name : text
[2018-01-08 21:26:00.302]from 0x00480D18
[2018-01-08 21:26:00.306]to 0x00480F28
[2018-01-08 21:26:00.310]va_to 0x24C48D20
[2018-01-08 21:26:00.313]Check data: Sora SC
[2018-01-08 21:26:00.318]game = 2
[2018-01-08 21:26:00.322]name : text
[2018-01-08 21:26:00.326]from 0x00498B54
[2018-01-08 21:26:00.329]to 0x00498F2C
[2018-01-08 21:26:00.334]va_to 0x01D9F35B
[2018-01-08 21:26:00.337]Check data: Sora 3RD
[2018-01-08 21:26:00.342]game = 3
[2018-01-08 21:26:00.346]name : text
[2018-01-08 21:26:00.350]from 0x00537C17
[2018-01-08 21:26:00.354]to 0x0053800D
[2018-01-08 21:26:00.358]va_to 0xB8C5FD31
[2018-01-08 21:26:00.363]Check data: Zero
[2018-01-08 21:26:00.367]game = 4
[2018-01-08 21:26:00.371]name : text
[2018-01-08 21:26:00.375]from 0x0089DCFB
[2018-01-08 21:26:00.379]to 0x0089E0BB
[2018-01-08 21:26:00.383]va_to 0x0089DD01
[2018-01-08 21:26:00.386]Check data: Zero JOYO
[2018-01-08 21:26:00.390]game = 4
[2018-01-08 21:26:00.394]name : text
[2018-01-08 21:26:00.398]from 0x0089DCFB
[2018-01-08 21:26:00.401]to 0x0089E0BB
[2018-01-08 21:26:00.405]va_to 0x0089DD01
[2018-01-08 21:26:00.409]Check data: Zero CubeJoy
[2018-01-08 21:26:00.412]game = 4
[2018-01-08 21:26:00.416]name : text
[2018-01-08 21:26:00.420]from 0x006A594B
[2018-01-08 21:26:00.424]to 0x006A5D0F
[2018-01-08 21:26:00.428]va_to 0x006A5951
[2018-01-08 21:26:00.432]Check data: Zero JP
[2018-01-08 21:26:00.436]game = 4
[2018-01-08 21:26:00.439]name : text
[2018-01-08 21:26:00.443]from 0x0089AF8B
[2018-01-08 21:26:00.447]to 0x0089B34B
[2018-01-08 21:26:00.451]va_to 0x0089AF91
[2018-01-08 21:26:00.454]Check data: Ao
[2018-01-08 21:26:00.458]game = 5
[2018-01-08 21:26:00.462]name : text
[2018-01-08 21:26:00.466]from 0x008BABEB
[2018-01-08 21:26:00.470]to 0x008BAE89
[2018-01-08 21:26:00.473]va_to 0x008BABF1
[2018-01-08 21:26:00.478]Check data: Ao JOYO
[2018-01-08 21:26:00.481]game = 5
[2018-01-08 21:26:00.485]name : text
[2018-01-08 21:26:00.489]from 0x008BEBEB
[2018-01-08 21:26:00.493]to 0x008BEE89
[2018-01-08 21:26:00.497]va_to 0x008BEBF1
[2018-01-08 21:26:00.501]Check data: TiTS FC Steam 20170505
[2018-01-08 21:26:00.505]game = 11
[2018-01-08 21:26:00.510]name : text
[2018-01-08 21:26:00.513]from 0x00483272
[2018-01-08 21:26:00.518]to 0x00483485
[2018-01-08 21:26:00.521]va_to 0xDBB1F40C
[2018-01-08 21:26:00.525]Check data: TiTS FC 20170828
[2018-01-08 21:26:00.529]game = 11
[2018-01-08 21:26:00.533]name : text
[2018-01-08 21:26:00.537]from 0x00489172
[2018-01-08 21:26:00.541]to 0x00489385
[2018-01-08 21:26:00.545]va_to 0x62FBA5B5
[2018-01-08 21:26:00.549]Check data: TiTS FC DX9 20170828
[2018-01-08 21:26:00.552]game = 21
[2018-01-08 21:26:00.556]name : text
[2018-01-08 21:26:00.560]from 0x0048EA12
[2018-01-08 21:26:00.563]to 0x0048EC25
[2018-01-08 21:26:00.567]va_to 0x00A46EF4
[2018-01-08 21:26:00.570]Check data: TiTS SC 20170828
[2018-01-08 21:26:00.574]game = 12
[2018-01-08 21:26:00.580]name : text
[2018-01-08 21:26:00.583]from 0x004B331A
[2018-01-08 21:26:00.587]to 0x004B3715
[2018-01-08 21:26:00.592]va_to 0x004B3715
[2018-01-08 21:26:00.596]name : dududu
[2018-01-08 21:26:00.600]from 0x004B55E9
[2018-01-08 21:26:00.604]to 0x00021A09
[2018-01-08 21:26:00.608]name : dlgse
[2018-01-08 21:26:00.611]from 0x004B5384
[2018-01-08 21:26:00.615]to 0x00021A09
[2018-01-08 21:26:00.618]name : aup
[2018-01-08 21:26:00.622]from 0x004F3F59
[2018-01-08 21:26:00.626]to 0x00471EB0
[2018-01-08 21:26:00.630]va_to 0x00471EB0
[2018-01-08 21:26:00.634]name : scode
[2018-01-08 21:26:00.638]from 0x0047856B
[2018-01-08 21:26:00.642]to 0x00000000
[2018-01-08 21:26:00.646]name : ldscn
[2018-01-08 21:26:00.650]from 0x00477553
[2018-01-08 21:26:00.654]to 0x00000000
[2018-01-08 21:26:00.659]name : ldscnB
[2018-01-08 21:26:00.663]from 0x00000000
[2018-01-08 21:26:00.666]to 0x00000000
[2018-01-08 21:26:00.670]name : ldscnB2
[2018-01-08 21:26:00.674]from 0x00000000
[2018-01-08 21:26:00.678]to 0x00000000
[2018-01-08 21:26:00.682]name : ldquiz
[2018-01-08 21:26:00.685]from 0x00000000
[2018-01-08 21:26:00.689]to 0x00000000
[2018-01-08 21:26:00.693]name : ldquizB
[2018-01-08 21:26:00.697]from 0x00000000
[2018-01-08 21:26:00.701]to 0x00000000
[2018-01-08 21:26:00.704]name : scnp
[2018-01-08 21:26:00.708]from 0x00000000
[2018-01-08 21:26:00.712]to 0x00000000
[2018-01-08 21:26:00.716]name : prst
[2018-01-08 21:26:00.720]from 0x004E3BFC
[2018-01-08 21:26:00.724]to 0x00000005
[2018-01-08 21:26:00.728]name : prst2
[2018-01-08 21:26:00.731]from 0x004C45FE
[2018-01-08 21:26:00.735]to 0x00000007
[2018-01-08 21:26:00.739]name : prst3
[2018-01-08 21:26:00.743]from 0x004D80DA
[2018-01-08 21:26:00.747]to 0x00000005
[2018-01-08 21:26:00.751]name : prst4
[2018-01-08 21:26:00.754]from 0x00000000
[2018-01-08 21:26:00.759]to 0x00000000
[2018-01-08 21:26:00.762]name : prst5
[2018-01-08 21:26:00.767]from 0x00000000
[2018-01-08 21:26:00.771]to 0x00000000
[2018-01-08 21:26:00.775]FeatureAddr: 0x00000000
[2018-01-08 21:26:00.778]Data found, num = 29, name = TiTS SC 20170828, game = 12
[2018-01-08 21:26:00.784]p = 0x27EFE1C0
[2018-01-08 21:26:00.788]p->p_d3dd = 0x006432B4
[2018-01-08 21:26:00.792]p->p_did = 0x00000000
[2018-01-08 21:26:00.796]p->p_Hwnd = 0x00643434
[2018-01-08 21:26:00.800]p->p_pDS = 0x0064332C
[2018-01-08 21:26:00.804]p->p_mute = 0x00000000
[2018-01-08 21:26:00.808]p->p_keys = 0x006034F8
[2018-01-08 21:26:00.812]p->p_global = 0x00000000
[2018-01-08 21:26:00.816]p->p_rnd_vlst = 0x00000000
[2018-01-08 21:26:00.820]d3dd = 0x0F42ED00
[2018-01-08 21:26:00.824]did = 0x00000000
[2018-01-08 21:26:00.828]Hwnd = 0x0021065E
[2018-01-08 21:26:00.832]pDS = 0x05640830
[2018-01-08 21:26:00.835]Now going to get d3dx Apis
[2018-01-08 21:26:00.840]Now going to load vorbisfile.dll ...
[2018-01-08 21:26:00.845]Loaded ov_open_callbacks = 0x25F310E0
[2018-01-08 21:26:00.849]Loaded ov_info = 0x25F34C20
[2018-01-08 21:26:00.853]Loaded ov_read = 0x25F34CA0
[2018-01-08 21:26:00.857]Loaded ov_clear = 0x25F31000
[2018-01-08 21:26:00.861]Loaded ov_pcm_total = 0x25F32DB0
[2018-01-08 21:26:00.869]change code at : 0x004B331A
[2018-01-08 21:26:00.874]change code at : 0x004B55E9
[2018-01-08 21:26:00.878]Set p_mute = 0x00613D13
[2018-01-08 21:26:00.881]*p_mute = 0x00010000
[2018-01-08 21:26:00.885]change code at : 0x004B5384
[2018-01-08 21:26:00.890]change code at : 0x004F3F59
[2018-01-08 21:26:00.894]change code at : 0x0047856B
[2018-01-08 21:26:00.898]change code at : 0x00477553
[2018-01-08 21:26:00.902]change code at : 0x004E3BFC
[2018-01-08 21:26:00.906]change code at : 0x004C45FE
[2018-01-08 21:26:00.910]change code at : 0x004D80DA
[2018-01-08 21:26:00.914]ApplyMemoryPatch2...
[2018-01-08 21:26:00.918]MemPatch, offset=0x005B5D7F, len_old=0x0022, , len_new=0x0024
[2018-01-08 21:26:00.923]Changed mem data at 0x005B5D7F
[2018-01-08 21:26:00.927]ApplyMemoryPatch2, End.
[2018-01-08 21:26:00.931]ApplyMemoryPatch Finished.
[2018-01-08 21:26:00.936]screen width = 1920
[2018-01-08 21:26:00.940]screen height = 1080
[2018-01-08 21:26:00.944]Font Size = 43
[2018-01-08 21:26:00.949]Add text, type = 0
[2018-01-08 21:26:00.954]Create new Text.
[2018-01-08 21:26:00.958]Text is Sora/Zero/Ao no Kiseki Voice Patch
[2018-01-08 21:26:00.962]Text width is 1387
[2018-01-08 21:26:00.966]top = 13, bottom = 70, left = 22, right = 1409
[2018-01-08 21:26:00.970]Add text, type = 0
[2018-01-08 21:26:00.974]Create new Text.
[2018-01-08 21:26:00.978]Text is Version: DEBUG 20180108
[2018-01-08 21:26:00.983]Text width is 938
[2018-01-08 21:26:00.987]top = 70, bottom = 127, left = 22, right = 960
[2018-01-08 21:26:00.991]Add text, type = 0
[2018-01-08 21:26:00.995]Create new Text.
[2018-01-08 21:26:01.000]Text is Current Game: Trails in the Sky SC (20170828)
[2018-01-08 21:26:01.005]Text width is 1836
[2018-01-08 21:26:01.009]top = 127, bottom = 184, left = 22, right = 1858
[2018-01-08 21:26:01.013]SoraVoice Started.
[2018-01-08 21:26:23.387]Stop is called.
[2018-01-08 21:26:25.774]Stop is called.
[2018-01-08 21:26:26.010]Stop is called.
[2018-01-08 21:26:55.409]Starting SoraVoice...
[2018-01-08 21:26:55.414]module info: base = 0x00400000, size = 0x02C1F000
[2018-01-08 21:26:55.418]Loading Config...
[2018-01-08 21:26:55.423]Config loaded
[2018-01-08 21:26:55.427]config.Volume = 100
[2018-01-08 21:26:55.431]config.OriginalVoice = 1
[2018-01-08 21:26:55.435]config.AutoPlay = 2
[2018-01-08 21:26:55.440]config.WaitTimePerChar = 60
[2018-01-08 21:26:55.444]config.WaitTimeDialog = 800
[2018-01-08 21:26:55.449]config.WaitTimeDialogVoice = 500
[2018-01-08 21:26:55.454]config.SkipVoice = 1
[2018-01-08 21:26:55.458]config.DisableDududu = 1
[2018-01-08 21:26:55.461]config.DisableDialogSE = 1
[2018-01-08 21:26:55.466]config.ShowInfo = 1
[2018-01-08 21:26:55.471]config.FontName = Microsoft Yahei
[2018-01-08 21:26:55.475]config.FontColor = 0xFFFFFFFF
[2018-01-08 21:26:55.479]config.EnableKeys = 1
[2018-01-08 21:26:55.483]config.SaveChange = 1
[2018-01-08 21:26:55.488]Open resource: voice/SoraData.ini
[2018-01-08 21:26:55.492]Resource openned, first = 0x236915E8, size = 0x37D6
[2018-01-08 21:26:55.522]ini file opened. 17
[2018-01-08 21:26:55.526]Check data: Sora FC
[2018-01-08 21:26:55.530]game = 1
[2018-01-08 21:26:55.535]name : text
[2018-01-08 21:26:55.539]from 0x00480D18
[2018-01-08 21:26:55.544]to 0x00480F28
[2018-01-08 21:26:55.548]va_to 0x5E07E3BE
[2018-01-08 21:26:55.552]Check data: Sora SC
[2018-01-08 21:26:55.556]game = 2
[2018-01-08 21:26:55.560]name : text
[2018-01-08 21:26:55.565]from 0x00498B54
[2018-01-08 21:26:55.570]to 0x00498F2C
[2018-01-08 21:26:55.574]va_to 0x032E7EE2
[2018-01-08 21:26:55.578]Check data: Sora 3RD
[2018-01-08 21:26:55.582]game = 3
[2018-01-08 21:26:55.586]name : text
[2018-01-08 21:26:55.590]from 0x00537C17
[2018-01-08 21:26:55.595]to 0x0053800D
[2018-01-08 21:26:55.599]va_to 0xEB53D41C
[2018-01-08 21:26:55.602]Check data: Zero
[2018-01-08 21:26:55.607]game = 4
[2018-01-08 21:26:55.610]name : text
[2018-01-08 21:26:55.615]from 0x0089DCFB
[2018-01-08 21:26:55.619]to 0x0089E0BB
[2018-01-08 21:26:55.624]va_to 0x0089DD01
[2018-01-08 21:26:55.628]Check data: Zero JOYO
[2018-01-08 21:26:55.631]game = 4
[2018-01-08 21:26:55.635]name : text
[2018-01-08 21:26:55.640]from 0x0089DCFB
[2018-01-08 21:26:55.644]to 0x0089E0BB
[2018-01-08 21:26:55.648]va_to 0x0089DD01
[2018-01-08 21:26:55.651]Check data: Zero CubeJoy
[2018-01-08 21:26:55.655]game = 4
[2018-01-08 21:26:55.660]name : text
[2018-01-08 21:26:55.664]from 0x006A594B
[2018-01-08 21:26:55.668]to 0x006A5D0F
[2018-01-08 21:26:55.673]va_to 0x006A5951
[2018-01-08 21:26:55.677]Check data: Zero JP
[2018-01-08 21:26:55.682]game = 4
[2018-01-08 21:26:55.685]name : text
[2018-01-08 21:26:55.689]from 0x0089AF8B
[2018-01-08 21:26:55.693]to 0x0089B34B
[2018-01-08 21:26:55.697]va_to 0x0089AF91
[2018-01-08 21:26:55.700]Check data: Ao
[2018-01-08 21:26:55.705]game = 5
[2018-01-08 21:26:55.709]name : text
[2018-01-08 21:26:55.713]from 0x008BABEB
[2018-01-08 21:26:55.717]to 0x008BAE89
[2018-01-08 21:26:55.720]va_to 0x008BABF1
[2018-01-08 21:26:55.724]Check data: Ao JOYO
[2018-01-08 21:26:55.728]game = 5
[2018-01-08 21:26:55.731]name : text
[2018-01-08 21:26:55.735]from 0x008BEBEB
[2018-01-08 21:26:55.739]to 0x008BEE89
[2018-01-08 21:26:55.742]va_to 0x008BEBF1
[2018-01-08 21:26:55.746]Check data: TiTS FC Steam 20170505
[2018-01-08 21:26:55.749]game = 11
[2018-01-08 21:26:55.753]name : text
[2018-01-08 21:26:55.757]from 0x00483272
[2018-01-08 21:26:55.760]to 0x00483485
[2018-01-08 21:26:55.765]va_to 0x2489BDC8
[2018-01-08 21:26:55.769]Check data: TiTS FC 20170828
[2018-01-08 21:26:55.773]game = 11
[2018-01-08 21:26:55.776]name : text
[2018-01-08 21:26:55.781]from 0x00489172
[2018-01-08 21:26:55.784]to 0x00489385
[2018-01-08 21:26:55.788]va_to 0x0BE0F978
[2018-01-08 21:26:55.791]Check data: TiTS FC DX9 20170828
[2018-01-08 21:26:55.795]game = 21
[2018-01-08 21:26:55.798]name : text
[2018-01-08 21:26:55.802]from 0x0048EA12
[2018-01-08 21:26:55.806]to 0x0048EC25
[2018-01-08 21:26:55.809]va_to 0x0049B2D8
[2018-01-08 21:26:55.813]Check data: TiTS SC 20170828
[2018-01-08 21:26:55.816]game = 12
[2018-01-08 21:26:55.820]name : text
[2018-01-08 21:26:55.824]from 0x004B331A
[2018-01-08 21:26:55.827]to 0x004B3715
[2018-01-08 21:26:55.831]va_to 0xDA1B3648
[2018-01-08 21:26:55.834]Check data: TiTS SC DX9 20170828
[2018-01-08 21:26:55.838]game = 22
[2018-01-08 21:26:55.841]name : text
[2018-01-08 21:26:55.845]from 0x004C25BA
[2018-01-08 21:26:55.849]to 0x004C29B5
[2018-01-08 21:26:55.852]va_to 0x004C29B5
[2018-01-08 21:26:55.856]name : dududu
[2018-01-08 21:26:55.860]from 0x004C4889
[2018-01-08 21:26:55.864]to 0x00021A09
[2018-01-08 21:26:55.868]name : dlgse
[2018-01-08 21:26:55.871]from 0x004C4624
[2018-01-08 21:26:55.875]to 0x00021A09
[2018-01-08 21:26:55.878]name : aup
[2018-01-08 21:26:55.882]from 0x00503149
[2018-01-08 21:26:55.885]to 0x00480FF0
[2018-01-08 21:26:55.889]va_to 0x00480FF0
[2018-01-08 21:26:55.893]name : scode
[2018-01-08 21:26:55.896]from 0x004876CB
[2018-01-08 21:26:55.900]to 0x00000000
[2018-01-08 21:26:55.904]name : ldscn
[2018-01-08 21:26:55.907]from 0x004866B3
[2018-01-08 21:26:55.911]to 0x00000000
[2018-01-08 21:26:55.915]name : ldscnB
[2018-01-08 21:26:55.918]from 0x00000000
[2018-01-08 21:26:55.922]to 0x00000000
[2018-01-08 21:26:55.926]name : ldscnB2
[2018-01-08 21:26:55.929]from 0x00000000
[2018-01-08 21:26:55.933]to 0x00000000
[2018-01-08 21:26:55.937]name : ldquiz
[2018-01-08 21:26:55.941]from 0x00000000
[2018-01-08 21:26:55.945]to 0x00000000
[2018-01-08 21:26:55.949]name : ldquizB
[2018-01-08 21:26:55.953]from 0x00000000
[2018-01-08 21:26:55.957]to 0x00000000
[2018-01-08 21:26:55.961]name : scnp
[2018-01-08 21:26:55.965]from 0x00000000
[2018-01-08 21:26:55.969]to 0x00000000
[2018-01-08 21:26:55.972]name : prst
[2018-01-08 21:26:55.976]from 0x004F2D51
[2018-01-08 21:26:55.979]to 0x00000005
[2018-01-08 21:26:55.983]name : prst2
[2018-01-08 21:26:55.986]from 0x004D379D
[2018-01-08 21:26:55.990]to 0x00000007
[2018-01-08 21:26:55.994]name : prst3
[2018-01-08 21:26:55.997]from 0x004E707E
[2018-01-08 21:26:56.001]to 0x00000005
[2018-01-08 21:26:56.007]name : prst4
[2018-01-08 21:26:56.016]from 0x00000000
[2018-01-08 21:26:56.020]to 0x00000000
[2018-01-08 21:26:56.024]name : prst5
[2018-01-08 21:26:56.029]from 0x00000000
[2018-01-08 21:26:56.033]to 0x00000000
[2018-01-08 21:26:56.038]FeatureAddr: 0x00000000
[2018-01-08 21:26:56.041]Data found, num = 29, name = TiTS SC DX9 20170828, game = 22
[2018-01-08 21:26:56.048]p = 0x2714E1C0
[2018-01-08 21:26:56.052]p->p_d3dd = 0x0060B544
[2018-01-08 21:26:56.055]p->p_did = 0x00000000
[2018-01-08 21:26:56.059]p->p_Hwnd = 0x0060B6C4
[2018-01-08 21:26:56.062]p->p_pDS = 0x0060B5BC
[2018-01-08 21:26:56.066]p->p_mute = 0x00000000
[2018-01-08 21:26:56.070]p->p_keys = 0x005CB768
[2018-01-08 21:26:56.073]p->p_global = 0x00000000
[2018-01-08 21:26:56.077]p->p_rnd_vlst = 0x00000000
[2018-01-08 21:26:56.081]d3dd = 0x1ECE2220
[2018-01-08 21:26:56.085]did = 0x00000000
[2018-01-08 21:26:56.088]Hwnd = 0x0024065E
[2018-01-08 21:26:56.093]pDS = 0x05720830
[2018-01-08 21:26:56.096]Now going to get d3dx Apis
[2018-01-08 21:26:56.101]Api D3DXCreateFontIndirect (Original:D3DXCreateFontIndirectW) loaded, address = 0x0F4F8AC3
[2018-01-08 21:26:56.104]Api D3DXCreateSprite (Original:D3DXCreateSprite) loaded, address = 0x0F4F89C7
[2018-01-08 21:26:56.108]Now going to load vorbisfile.dll ...
[2018-01-08 21:26:56.113]Loaded ov_open_callbacks = 0x0EC010E0
[2018-01-08 21:26:56.117]Loaded ov_info = 0x0EC04C20
[2018-01-08 21:26:56.120]Loaded ov_read = 0x0EC04CA0
[2018-01-08 21:26:56.124]Loaded ov_clear = 0x0EC01000
[2018-01-08 21:26:56.128]Loaded ov_pcm_total = 0x0EC02DB0
[2018-01-08 21:26:56.135]change code at : 0x004C25BA
[2018-01-08 21:26:56.139]change code at : 0x004C4889
[2018-01-08 21:26:56.143]Set p_mute = 0x005DBFA3
[2018-01-08 21:26:56.146]*p_mute = 0x00010000
[2018-01-08 21:26:56.150]change code at : 0x004C4624
[2018-01-08 21:26:56.153]change code at : 0x00503149
[2018-01-08 21:26:56.157]change code at : 0x004876CB
[2018-01-08 21:26:56.161]change code at : 0x004866B3
[2018-01-08 21:26:56.165]change code at : 0x004F2D51
[2018-01-08 21:26:56.169]change code at : 0x004D379D
[2018-01-08 21:26:56.173]change code at : 0x004E707E
[2018-01-08 21:26:56.177]ApplyMemoryPatch2...
[2018-01-08 21:26:56.180]MemPatch, offset=0x0057C80F, len_old=0x0022, , len_new=0x0024
[2018-01-08 21:26:56.184]Changed mem data at 0x0057C80F
[2018-01-08 21:26:56.188]ApplyMemoryPatch2, End.
[2018-01-08 21:26:56.191]ApplyMemoryPatch Finished.
[2018-01-08 21:26:56.196]screen width = 1920
[2018-01-08 21:26:56.200]screen height = 1080
[2018-01-08 21:26:56.204]Font Size = 43
[2018-01-08 21:26:56.208]Add text, type = 0
[2018-01-08 21:26:56.212]Create new Text.
[2018-01-08 21:26:56.216]Text is Sora/Zero/Ao no Kiseki Voice Patch
[2018-01-08 21:26:56.220]Text width is 1387
[2018-01-08 21:26:56.223]top = 13, bottom = 70, left = 22, right = 1409
[2018-01-08 21:26:56.227]Add text, type = 0
[2018-01-08 21:26:56.231]Create new Text.
[2018-01-08 21:26:56.234]Text is Version: DEBUG 20180108
[2018-01-08 21:26:56.238]Text width is 938
[2018-01-08 21:26:56.241]top = 70, bottom = 127, left = 22, right = 960
[2018-01-08 21:26:56.246]Add text, type = 0
[2018-01-08 21:26:56.249]Create new Text.
[2018-01-08 21:26:56.253]Text is Current Game: Trails in the Sky SC (DX9 20170828)
[2018-01-08 21:26:56.257]Text width is 1999
[2018-01-08 21:26:56.260]top = 127, bottom = 184, left = 22, right = 2021
[2018-01-08 21:26:56.264]SoraVoice Started.
[2018-01-08 21:27:14.800]Stop is called.
[2018-01-08 21:27:16.982]Stop is called.
[2018-01-08 21:27:17.366]Stop is called.
[2018-01-08 21:27:18.832]Stop is called.
[2018-01-08 21:27:19.349]Stop is called.
[2018-01-08 21:27:19.748]Stop is called.
[2018-01-08 21:27:21.065]Stop is called.
[2018-01-08 21:27:21.448]Stop is called.
[2018-01-08 21:27:22.198]Stop is called.
[2018-01-08 21:27:22.564]Stop is called.
[2018-01-08 21:27:22.914]Stop is called.
[2018-01-08 21:27:23.281]Stop is called.
[2018-01-08 21:27:23.614]Stop is called.
[2018-01-08 21:27:24.014]Stop is called.
[2018-01-08 21:27:24.364]Stop is called.
[2018-01-08 21:27:24.747]Stop is called.
[2018-01-08 21:27:25.130]Stop is called.
[2018-01-08 21:27:25.497]Stop is called.
[2018-01-08 21:27:25.663]Stop is called.
[2018-01-08 21:27:26.063]Stop is called.
[2018-01-08 21:27:26.430]Stop is called.
[2018-01-08 21:27:26.647]Stop is called.
[2018-01-08 21:27:27.413]Stop is called.
[2018-01-08 21:27:27.796]Stop is called.
[2018-01-08 21:27:28.163]Stop is called.
[2018-01-08 21:27:28.529]Stop is called.
[2018-01-08 21:27:29.613]Stop is called.
[2018-01-08 21:27:29.829]Stop is called.
[2018-01-08 21:27:30.079]Stop is called.
[2018-01-08 21:27:30.328]Stop is called.
[2018-01-08 21:27:30.529]Stop is called.
[2018-01-08 21:27:31.195]Stop is called.
[2018-01-08 21:27:31.445]Stop is called.
[2018-01-08 21:27:31.645]Stop is called.
[2018-01-08 21:27:31.794]Stop is called.
[2018-01-08 21:27:32.478]Stop is called.
[2018-01-08 21:27:32.727]Stop is called.
[2018-01-08 21:27:32.928]Stop is called.
[2018-01-08 21:27:33.078]Stop is called.
[2018-01-08 21:27:33.227]Stop is called.
[2018-01-08 21:27:33.394]Stop is called.
[2018-01-08 21:27:33.611]Stop is called.
[2018-01-08 21:27:33.761]Stop is called.
[2018-01-08 21:27:33.911]Stop is called.
[2018-01-08 21:27:34.111]Stop is called.
[2018-01-08 21:27:34.261]Stop is called.
[2018-01-08 21:27:34.377]Stop is called.
[2018-01-08 21:27:34.544]Stop is called.
[2018-01-08 21:27:34.743]Stop is called.
[2018-01-08 21:27:34.993]Stop is called.
[2018-01-08 21:27:35.160]Stop is called.
[2018-01-08 21:27:35.327]Stop is called.
[2018-01-08 21:27:35.593]Stop is called.
[2018-01-08 21:27:36.126]Stop is called.

**Comment by ZhenjianYang** [comment]
Thank you for your reports.
There was a bug with version 20180101.
With this bug, the game loaded original scripts instead of voice scripts. 
So voice patch didn't work.
This bug has been fixed in the [latest release](https://github.com/ZhenjianYang/SoraVoice/releases/latest).

**Comment by actrois** [comment]
I seem to still have this problem even in the latest version. No voice in any dialogue. But in my case, this is also the case when using the old version with SoraDataEx.ini 
Any heads up?

**Comment by Shadowkillerdragon** [comment]
I just updated mine and tested with the current release that doesn't use SoraDataEx.ini and it works and loads the voices on FC. Does it show that the SoraVoice gets load on game startup in the top left?

**Comment by ZhenjianYang** [comment]
@actrois 
Have you updated your game to the latest version?

**Comment by actrois** [comment]
Yes, I've used both the latest GOG and Steam version to no avail. 
Also yes, the "Sora/Ao/Zero no Kiseki Voice Patch" text appeared in the game’s startup and when I press the hotkeys it shows the informations as said in ed_voice.ini

**Comment by ZhenjianYang** [comment]
Do the voice scripts and voice files correctly installed?

**Comment by actrois** [comment]
it should be, unless I miss anything vital:
dinput8.dll in the installation folder, 
voice folder with dll, scena, ogg folder, ed_voice.dll and ed_voice.ini

**Comment by ZhenjianYang** [comment]
This is strange...
@actrois Can you open a new issue for this problem?
It will help a lot if you can post the capture of the folders voice, scena, and ogg

**Comment by actrois** [comment]
okay
